import { useEffect } from 'react'
import { createPortal } from 'react-dom'
import { useApp } from '@/data/store'
import { branchById, patientById, treatmentTypeById, userById } from '@/data/selectors'
import { calculateAge, formatDate } from '@/lib/dates'
import type { Treatment } from '@/data/types'

/**
 * A printable prescription.
 *
 * The doctor's output is a piece of paper the patient walks out with — a
 * prescription that only exists inside the software has not been "released".
 * This renders a clean sheet, hidden on screen and visible only to the
 * printer, then triggers the print dialog.
 */
export function PrescriptionPrint({
  treatment,
  onDone,
}: {
  treatment: Treatment
  onDone: () => void
}) {
  const { db } = useApp()

  const patient = patientById(db, treatment.patientId)
  const doctor = userById(db, treatment.doctorId)
  const branch = branchById(db, treatment.branchId)
  const type = treatmentTypeById(db, treatment.treatmentTypeId)

  useEffect(() => {
    // Let the sheet paint before handing over to the print dialog.
    const timer = setTimeout(() => {
      window.print()
      onDone()
    }, 120)

    return () => clearTimeout(timer)
  }, [onDone])

  if (!patient) return null

  return createPortal(
    <div className="print-sheet" role="document" aria-label="Prescription">
      <header className="print-header">
        <div>
          <p className="print-brand">{db.settings.name}</p>
          <p className="print-sub">{db.settings.tagline}</p>
        </div>
        <div className="print-branch">
          <p>{branch?.name}</p>
          <p>{branch?.address}</p>
          <p>{branch?.phone}</p>
        </div>
      </header>

      <div className="print-meta">
        <div>
          <span className="print-label">Patient</span>
          <p className="print-value">{patient.name}</p>
          <p className="print-small">
            {patient.code}
            {patient.dob ? ` · ${calculateAge(patient.dob)} years` : ''}
            {` · ${patient.gender}`}
          </p>
        </div>
        <div>
          <span className="print-label">Date</span>
          <p className="print-value">{formatDate(treatment.performedAt)}</p>
          <p className="print-small">{type?.name}</p>
        </div>
        <div>
          <span className="print-label">Prescribed by</span>
          <p className="print-value">{doctor?.name}</p>
          <p className="print-small">{doctor?.specialisation}</p>
        </div>
      </div>

      {patient.allergies.length > 0 && (
        <p className="print-allergies">
          <strong>Allergies:</strong> {patient.allergies.join(', ')}
        </p>
      )}

      <h2 className="print-rx">℞</h2>

      <table className="print-table">
        <thead>
          <tr>
            <th style={{ width: '4%' }}>#</th>
            <th style={{ width: '32%' }}>Medication</th>
            <th style={{ width: '16%' }}>Dosage</th>
            <th style={{ width: '30%' }}>Frequency</th>
            <th style={{ width: '18%' }}>Duration</th>
          </tr>
        </thead>
        <tbody>
          {treatment.prescription.map((item, i) => (
            <tr key={item.id}>
              <td>{i + 1}</td>
              <td>
                <strong>{item.medication}</strong>
                {item.instructions && <div className="print-instructions">{item.instructions}</div>}
              </td>
              <td>{item.dosage || '—'}</td>
              <td>{item.frequency || '—'}</td>
              <td>{item.durationDays} days</td>
            </tr>
          ))}
        </tbody>
      </table>

      {treatment.nextVisitInDays ? (
        <p className="print-next">
          <strong>Next visit:</strong> in {treatment.nextVisitInDays} days
        </p>
      ) : null}

      <footer className="print-footer">
        <div className="print-sign">
          <div className="print-sign-line" />
          <p>{doctor?.name}</p>
          <p className="print-small">Signature</p>
        </div>
        <p className="print-disclaimer">
          Generated by {db.settings.name} — prototype. Not a valid medical document.
        </p>
      </footer>
    </div>,
    document.body,
  )
}
